conditions_dict = {
	'cta_drinking_familiar':{
		'brains':[
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-216','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-217','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-218','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-220','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-221','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-222','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-976','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-977','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-978','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-979','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-980','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-984','imaging_request':'imaging_request_1'},
		]
	},
	'cta_drinking_novel':{
		'brains':[
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-211','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-212','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-213','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-223','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-224','imaging_request':'imaging_request_3'},
			{'request_name':'zimmerman_05','sample_name':'zimmerman_05-225','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-981','imaging_request':'imaging_request_3'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-982','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-983','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-985','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-986','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_08','sample_name':'zimmerman_08-987','imaging_request':'imaging_request_1'},
		]
	},
	'cta_licl_familiar':{
		'brains':[
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-930','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-931','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-932','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-933','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-934','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-935','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-991','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-992','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-993','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-994','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-995','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-997','imaging_request':'imaging_request_1'},
		]
	},
	'cta_licl_novel':{
		'brains':[
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-926','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-927','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-928','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-929','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-936','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_09','sample_name':'zimmerman_09-937','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-949','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-988','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-989','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-990','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-998','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_11','sample_name':'zimmerman_11-999','imaging_request':'imaging_request_1'},
		]
	},
	'cta_cgrp_familiar':{
		'brains':[
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-233','imaging_request':'imaging_request_1','pbn_fos':3745},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-234','imaging_request':'imaging_request_1','pbn_fos':1735},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-235','imaging_request':'imaging_request_1','pbn_fos':2862},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-246','imaging_request':'imaging_request_1','pbn_fos':1936},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-247','imaging_request':'imaging_request_1','pbn_fos':1787},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-248','imaging_request':'imaging_request_1','pbn_fos':1905},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-239','imaging_request':'imaging_request_1','pbn_fos':1885},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-249','imaging_request':'imaging_request_1','pbn_fos':1186},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-250','imaging_request':'imaging_request_1','pbn_fos':2007},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-251','imaging_request':'imaging_request_1','pbn_fos':341},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-252','imaging_request':'imaging_request_1','pbn_fos':2517},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-253','imaging_request':'imaging_request_1','pbn_fos':1066},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-254','imaging_request':'imaging_request_1','pbn_fos':2179},
		]
	},
	'cta_cgrp_novel':{
		'brains':[
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-240','imaging_request':'imaging_request_1','pbn_fos':1677},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-241','imaging_request':'imaging_request_1','pbn_fos':968},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-242','imaging_request':'imaging_request_1','pbn_fos':2183},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-243','imaging_request':'imaging_request_1','pbn_fos':1855},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-244','imaging_request':'imaging_request_1','pbn_fos':2445},
			{'request_name':'zimmerman_12','sample_name':'zimmerman_12-245','imaging_request':'imaging_request_1','pbn_fos':1962},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-255','imaging_request':'imaging_request_1','pbn_fos':1336},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-256','imaging_request':'imaging_request_1','pbn_fos':1035},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-257','imaging_request':'imaging_request_1','pbn_fos':1897},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-258','imaging_request':'imaging_request_1','pbn_fos':1110},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-259','imaging_request':'imaging_request_1','pbn_fos':1452},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-260','imaging_request':'imaging_request_1','pbn_fos':1697},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-261','imaging_request':'imaging_request_1','pbn_fos':2746},
			{'request_name':'zimmerman_14','sample_name':'zimmerman_14-262','imaging_request':'imaging_request_1','pbn_fos':1204},
		]
	},
	'cta_retrieval_familiar':{
		'brains':[
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-564','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-565','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-566','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-570','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-571','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-572','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-065','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-066','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-068','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-069','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-070','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-071','imaging_request':'imaging_request_1'},
		]
	},
	'cta_retrieval_novel':{
		'brains':[
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-567','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-568','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-569','imaging_request':'imaging_request_2'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-573','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-574','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_15','sample_name':'zimmerman_15-575','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-064','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-067','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-072','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-073','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-074','imaging_request':'imaging_request_1'},
			{'request_name':'zimmerman_16','sample_name':'zimmerman_16-075','imaging_request':'imaging_request_1'},
		]
	}
}
